### PR TITLE
Field: change text field max length

### PR DESCRIPTION
**Pull request by christopher-hopper**
## Proposed Changes

Add methods to provide the following Field helpers:

1. Get and Set field config data
2. Change the max length of a Text field, even when it has stored data

## Motivation

I had a project where we needed to make the max length for some text fields longer, extending them from 150 to 255 chars. This cannot be done through the Drupal Field UI or Features when the field is shared and/or has data stored in it. However it is possible with some custom Database queries.

### CODE REVIEW

**Comment by AlexSkrypnyk** [comment]
@christopher-hopper could you please enable a build for this project on CircleCI so that this PR could pass it.

**Comment by christopher-hopper** [comment]
Why can't CircleCI build and test using your current config? Doesn't it run tests for pull requests? Have you disabled something? I've never had to do this for other projects I've forked and then submitted back PRs for.

**Comment by christopher-hopper** [comment]
Hey @alexdesignworks you can fix this yourself for all of us I think. Try this:

:black_circle: Build forked pull requests
:white_circle: Pass secrets to builds from forked pull requests

selection_186

Play around with those. Understand the implications, see what happens.

**Comment by AlexSkrypnyk** [comment]
@christopher-hopper I've updated project settings on circle. thank you. But in order to run a build, we need to bump this branch. In order to speed things up, I have cherry-picked your commits into another PR https://github.com/alexdesignworks/drupal_helpers/pull/27. If it passes - I will merge and close both PRs. Apologies for all the fuss.

**Comment by AlexSkrypnyk** [comment]
merged as #27

**Pull request closed without merging**
